### ISSUE TITLE
Bug: 3.0.9 dist输出文件里的SignUpDto.js的文件名的大小写出错了，升级后项目无法构建

### ISSUE THREAD

**Issue by timeswind** [Authing/authing-node-sdk#19]
### Description
3.0.9版本升级后发现 dist输出文件里的SignUpDto.js的文件名的大小写出错了，变成了SignupDto.js，U变成了小写升级后项目无法构建

**Minimal code-snippet showcasing the problem**
 

```ts

```

**Comment by guojinlong** [comment]
+1

**Comment by willin** [comment]
fixed: v3.0.10
